cartasDict = {
    1: {"tipo": "Detective", "carta": "Harley Quin Wildcard", "cantidad": 4, "bocaArriba": False, "ubicacion": "mazo"},
    2: {"tipo": "Detective", "carta": "Adriane Oliver", "cantidad": 3, "bocaArriba": False, "ubicacion": "mazo"},
    3: {"tipo": "Detective", "carta": "Miss Marple", "cantidad": 3, "bocaArriba": False, "ubicacion": "mazo"},
    4: {"tipo": "Detective", "carta": "Parker Pyne", "cantidad": 3, "bocaArriba": False, "ubicacion": "mazo"},
    5: {"tipo": "Detective", "carta": "Tommy Beresford", "cantidad": 2, "bocaArriba": False, "ubicacion": "mazo"},
    6: {"tipo": "Detective", "carta": "Lady Eileen \"Bundle\" Brent", "cantidad": 3, "bocaArriba": False, "ubicacion": "mazo"},
    7: {"tipo": "Detective", "carta": "Tuppence Beresford", "cantidad": 2, "bocaArriba": False, "ubicacion": "mazo"},
    8: {"tipo": "Detective", "carta": "Hercule Poirot", "cantidad": 3, "bocaArriba": False, "ubicacion": "mazo"},
    9: {"tipo": "Detective", "carta": "Mr Satterthwaite", "cantidad": 2, "bocaArriba": False, "ubicacion": "mazo"},
    10: {"tipo": "Instant", "carta": "Not so fast", "cantidad": 10, "bocaArriba": False, "ubicacion": "mazo"},
    11: {"tipo": "Deviuos", "carta": "Blackmailed", "cantidad": 1, "bocaArriba": False, "ubicacion": "mazo"},
    12: {"tipo": "Deviuos", "carta": "Social Faux Pas", "cantidad": 3, "bocaArriba": False, "ubicacion": "mazo"},
    13: {"tipo": "Event", "carta": "Delay the murderer's espace!", "cantidad": 3, "bocaArriba": False, "ubicacion": "mazo"},
    14: {"tipo": "Event", "carta": "Point your suspicions", "cantidad": 3, "bocaArriba": False, "ubicacion": "mazo"},
    15: {"tipo": "Event", "carta": "Dead card folly", "cantidad": 3, "bocaArriba": False, "ubicacion": "mazo"},
    16: {"tipo": "Event", "carta": "Another Victim", "cantidad": 2, "bocaArriba": False, "ubicacion": "mazo"},
    17: {"tipo": "Event", "carta": "Look into the ashes", "cantidad": 3, "bocaArriba": False, "ubicacion": "mazo"},
    18: {"tipo": "Event", "carta": "Card trade", "cantidad": 3, "bocaArriba": False, "ubicacion": "mazo"},
    19: {"tipo": "Event", "carta": "And then there was one more...", "cantidad": 2, "bocaArriba": False, "ubicacion": "mazo"},
    20: {"tipo": "Event", "carta": "Early train to paddington", "cantidad": 2, "bocaArriba": False, "ubicacion": "mazo"},
    21: {"tipo": "Event", "carta": "Cards off the table", "cantidad": 1, "bocaArriba": False, "ubicacion": "mazo"},
}